# Generated by Django 5.2.3 on 2025-06-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_project_creator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckListItem',
        ),
    ]
